/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.glyaxz.gesty;

import java.awt.Button;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.MouseInputAdapter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialLiteTheme;

/**
 *
 * @author Javier Garcia
 */
public class App extends javax.swing.JFrame {
    public Empleado logged;
    GestyConnector gc;
    static App app;
    Company company;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        app = this;
        app.checkRef();
        ico.setIcon(new ImageIcon("logo.png"));
        app.setIconImage(new ImageIcon("logo.png").getImage());
        printTasksTable(null);
    }

    public App(Empleado logged, GestyConnector gc) {
        app = this;
        this.logged = logged;
        System.out.println(" " + logged);
        this.gc = gc;
        initComponents();
        setLocationRelativeTo(null);
        app.checkRef();
        logged.setCompany();
        company = gc.getCompany(logged);
        ico.setIcon(new ImageIcon("logo.png"));
        lblCompany.setText(logged.getCompany().getName());

        // try {
        //     myPicture = ImageIO.read(new File("logo.png"));
        //     ico = new JLabel(new ImageIcon(myPicture));
        // } catch (IOException ex) {
        //     Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        // }
    }

    MouseListener ml = new MouseListener() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                System.out.println("double clicked");
                int row = jtProjects.getSelectedRow();
    
                List<Project> projects = logged.getCompany().getProjects();
                for (Project p : projects) {
                    String value = String.valueOf(jtProjects.getValueAt(row, 0));
                    if (p.getName().equals(value)) {
                        jpProjects.setVisible(false);
                        printTasksTable(p);
                        jpTasks.setVisible(true);
                        break; // Salir del bucle si se encuentra el proyecto correspondiente
                    }
                }
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void mouseExited(MouseEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pnlOptions = new javax.swing.JDialog();
        jpApp = new javax.swing.JPanel();
        ico = new javax.swing.JLabel();
        btnTareas = new javax.swing.JButton();
        btnProjects = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpProjects = new javax.swing.JPanel();
        jspProjects = new javax.swing.JScrollPane();
        jtProjects = new javax.swing.JTable();
        jpTasks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTasks = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        btnChat = new javax.swing.JButton();
        jpRef = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRefAccept = new javax.swing.JButton();
        txtRefUser = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        pnlOptions.setMinimumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions.getContentPane());
        pnlOptions.getContentPane().setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jpApp.setMinimumSize(new java.awt.Dimension(800, 600));
        jpApp.setLayout(null);

        ico.setMinimumSize(new java.awt.Dimension(100, 100));
        jpApp.add(ico);
        ico.setBounds(50, 50, 100, 100);

        btnTareas.setText("Tareas");
        btnTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasActionPerformed(evt);
            }
        });
        jpApp.add(btnTareas);
        btnTareas.setBounds(40, 200, 120, 40);

        btnProjects.setText("Proyectos");
        btnProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectsActionPerformed(evt);
            }
        });
        jpApp.add(btnProjects);
        btnProjects.setBounds(40, 280, 120, 40);

        btnOptions.setText("Opciones");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });
        jpApp.add(btnOptions);
        btnOptions.setBounds(40, 360, 120, 40);

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jpApp.add(btnExit);
        btnExit.setBounds(40, 440, 120, 40);

        jpProjects.setLayout(null);

        jspProjects.setBorder(null);
        jspProjects.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspProjects.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jtProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Proyectos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspProjects.setViewportView(jtProjects);
        if (jtProjects.getColumnModel().getColumnCount() > 0) {
            jtProjects.getColumnModel().getColumn(0).setResizable(false);
        }

        jpProjects.add(jspProjects);
        jspProjects.setBounds(0, 0, 500, 450);

        jLayeredPane1.add(jpProjects);
        jpProjects.setBounds(0, 0, 506, 449);

        jpTasks.setLayout(null);

        jtTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarea", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTasks);
        if (jtTasks.getColumnModel().getColumnCount() > 0) {
            jtTasks.getColumnModel().getColumn(0).setResizable(false);
            jtTasks.getColumnModel().getColumn(1).setResizable(false);
        }

        jpTasks.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 452, 402);

        jLayeredPane1.add(jpTasks);
        jpTasks.setBounds(0, 0, 510, 450);

        jpApp.add(jLayeredPane1);
        jLayeredPane1.setBounds(230, 80, 510, 450);

        jLabel2.setText("Empresa:");
        jpApp.add(jLabel2);
        jLabel2.setBounds(30, 560, 60, 20);
        jpApp.add(lblCompany);
        lblCompany.setBounds(90, 560, 130, 20);

        btnChat.setText("Abrir Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        jpApp.add(btnChat);
        btnChat.setBounds(620, 550, 110, 30);

        jpRef.setMinimumSize(new java.awt.Dimension(800, 600));
        jpRef.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa a tu empresa");
        jpRef.add(jLabel1);
        jLabel1.setBounds(285, 137, 260, 58);

        btnRefAccept.setText("Aceptar");
        btnRefAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefAcceptActionPerformed(evt);
            }
        });
        jpRef.add(btnRefAccept);
        btnRefAccept.setBounds(360, 440, 120, 40);

        txtRefUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtRefUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRefUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefUserActionPerformed(evt);
            }
        });
        jpRef.add(txtRefUser);
        txtRefUser.setBounds(290, 240, 250, 100);

        jMenu4.setText("GestY");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setMnemonic('T');
        jMenuItem1.setText("Tareas");
        jMenuItem1.setToolTipText("Ir a Tareas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setMnemonic('P');
        jMenuItem2.setText("Proyectos");
        jMenuItem2.setToolTipText("Ir a Proyectos");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Opciones");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRefUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefUserActionPerformed

    private void btnRefAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefAcceptActionPerformed
        if(gc.setUserRef(logged, txtRefUser.getText())){
            reloadApp();
            loadApp();
        }
    }//GEN-LAST:event_btnRefAcceptActionPerformed

    private void btnTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTareasActionPerformed

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
        // TODO add your handling code here:        
        pnlOptions.setVisible(true);
    }//GEN-LAST:event_btnOptionsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exitApp();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectsActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtProjects.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        List<Project> projects = gc.getProjects(logged);
        
        for (Project p : projects) {
            JLabel label = new JLabel(p.getName());
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    System.out.println("double clicked");
                    int row = jtProjects.getSelectedRow();
                    String projectName = (String) jtProjects.getValueAt(row, 0);

                    // Realizar acciones con el nombre del proyecto seleccionado
                }
            });
            TableCellRenderer renderer = new LabelTableCellRenderer();
            jtProjects.getColumnModel().getColumn(0).setCellRenderer(renderer);
            model.addRow(new JLabel[] { label });
        }
        
    }//GEN-LAST:event_btnProjectsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        exitApp();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        pnlOptions.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        String empresa = company.getName();
        String topic = "gesty/" + empresa.toLowerCase().replace(' ', '-');
        openChat(topic);
    }//GEN-LAST:event_btnChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialLiteTheme()));
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //
            }
        });
        
    }

    public void setLogged(Empleado logged){
        this.logged = logged;
    }
    public Empleado getLogged(){
        return this.logged;
    }
    public GestyConnector getConnector(){
        return this.gc;
    }
    public void setConnector(GestyConnector gc){
        this.gc = gc;
    }
    public void checkRef(){
        if(gc.hasRef(this.logged)){
            app.jpApp.setVisible(true);
            app.jpRef.setVisible(false);
        }else{
            app.jpApp.setVisible(false);
            app.jpRef.setVisible(true);
        }
    }

    public void reloadApp(){
        Thread wait = new Thread( () -> {
            try{
                Thread.sleep(1000);
            }catch(InterruptedException e){
                e.printStackTrace();
            }
        });
        wait.run();
        System.out.println("DEBUG: " + "WIP -> FUNCTION TO UPDATE APP WHEN UPDATE COMPANY_REF");
    }
    public void loadApp(){
        jpRef.setVisible(false);
        jpApp.setVisible(true);
    }
    
    public void exitApp(){
        System.exit(0);
    }
    
    public void openChat(String topic){
        Chat chat = new Chat(logged, topic);
        chat.setLocationRelativeTo(null);
        chat.setVisible(true);
    }
    
    public void printTasksTable(Project project){
        DefaultTableModel model = (DefaultTableModel) jtTasks.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        if(project == null){
            List<Project> projects = logged.getCompany().getProjects();
            projects.forEach(p -> {
                List<Task> tasks = p.getTasks();
                tasks.forEach(t -> {
                    model.addRow(new Object[]{t.getName(), p.getName()});
                });
            });
        }else{
            List<Task> tasks = project.getTasks();
            tasks.forEach(t -> {
                model.addRow(new Object[]{t.getName(), project.getName()});
            });
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnProjects;
    private javax.swing.JButton btnRefAccept;
    private javax.swing.JButton btnTareas;
    private javax.swing.JLabel ico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpApp;
    private javax.swing.JPanel jpProjects;
    private javax.swing.JPanel jpRef;
    private javax.swing.JPanel jpTasks;
    private javax.swing.JScrollPane jspProjects;
    private javax.swing.JTable jtProjects;
    private javax.swing.JTable jtTasks;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JDialog pnlOptions;
    private javax.swing.JTextField txtRefUser;
    // End of variables declaration//GEN-END:variables
}
