/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.glyaxz.gesty;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Javier Garcia
 */
public class App extends javax.swing.JFrame {
    public Empleado logged;
    GestyConnector gc;
    static App app;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        app = this;
        app.checkRef();
        BufferedImage myPicture;
        try {
            myPicture = ImageIO.read(new File("logo.png"));
            ico = new JLabel(new ImageIcon(myPicture));
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public App(Empleado logged, GestyConnector gc) {
        app = this;
        this.logged = logged;
        System.out.println(logged);
        this.gc = gc;
        initComponents();
        setLocationRelativeTo(null);
        app.checkRef();
        BufferedImage myPicture;
        // try {
        //     myPicture = ImageIO.read(new File("logo.png"));
        //     ico = new JLabel(new ImageIcon(myPicture));
        // } catch (IOException ex) {
        //     Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        // }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpApp = new javax.swing.JPanel();
        ico = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jpRef = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRefAccept = new javax.swing.JButton();
        txtRefUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jpApp.setMinimumSize(new java.awt.Dimension(800, 600));
        jpApp.setLayout(null);

        ico.setMinimumSize(new java.awt.Dimension(800, 600));
        jpApp.add(ico);
        ico.setBounds(6, 6, 102, 85);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpApp.add(jButton1);
        jButton1.setBounds(350, 280, 75, 23);

        jpRef.setMinimumSize(new java.awt.Dimension(800, 600));
        jpRef.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa a tu empresa");
        jpRef.add(jLabel1);
        jLabel1.setBounds(285, 137, 260, 58);

        btnRefAccept.setText("Aceptar");
        btnRefAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefAcceptActionPerformed(evt);
            }
        });
        jpRef.add(btnRefAccept);
        btnRefAccept.setBounds(360, 440, 120, 40);

        txtRefUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtRefUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRefUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefUserActionPerformed(evt);
            }
        });
        jpRef.add(txtRefUser);
        txtRefUser.setBounds(290, 240, 250, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRefUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefUserActionPerformed

    private void btnRefAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefAcceptActionPerformed
        if(gc.setUserRef(logged, txtRefUser.getText())){
            reloadApp();
            loadApp();
        }
    }//GEN-LAST:event_btnRefAcceptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("EMPLEADO PRE GETCOMPANY: " + logged.getEmail());
        boolean test = gc.getCompany(logged);
        System.out.println(test);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new App().setVisible(true);
        //     }
        // });
        
    }

    public void setLogged(Empleado logged){
        this.logged = logged;
    }
    public Empleado getLogged(){
        return this.logged;
    }
    public GestyConnector getConnector(){
        return this.gc;
    }
    public void setConnector(GestyConnector gc){
        this.gc = gc;
    }
    public void checkRef(){
        if(gc.hasRef(this.logged)){
            System.out.println("tiene ref");
            app.jpApp.setVisible(true);
            app.jpRef.setVisible(false);
        }else{
            System.out.println("no tiene ref");
            app.jpApp.setVisible(false);
            app.jpRef.setVisible(true);
        }
    }

    public void reloadApp(){
        Thread wait = new Thread( () -> {
            try{
                Thread.sleep(1000);
            }catch(InterruptedException e){
                e.printStackTrace();
            }
        });
        wait.run();
        System.out.println("WIP -> FUNCTION TO UPDATE APP WHEN UPDATE COMPANY_REF");
    }
    public void loadApp(){
        jpRef.setVisible(false);
        jpApp.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefAccept;
    private javax.swing.JLabel ico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpApp;
    private javax.swing.JPanel jpRef;
    private javax.swing.JTextField txtRefUser;
    // End of variables declaration//GEN-END:variables
}
