/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.glyaxz.gesty;

import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URI;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialLiteTheme;

/**
 *
 * @author Javier Garcia
 */
public class App extends javax.swing.JFrame {
    public Empleado logged;
    GestyConnector gc;
    static App app;
    Company company;
    String topic;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        app = this;
        app.checkRef();
        ico.setIcon(new ImageIcon("logo.png"));
        app.setIconImage(new ImageIcon("logo.png").getImage());
        printTasksTable();
    }

    public App(Empleado logged, GestyConnector gc) {
        app = this;
        this.logged = logged;
        this.gc = gc;
        initComponents();
        setLocationRelativeTo(null);
        company = gc.getCompany(logged);
        app.checkRef();
        getData();
        this.setTitle("GestY - " + logged.getCompany().getName());
        this.setIconImage(new ImageIcon("logo.png").getImage());
        ico.setIcon(new ImageIcon("logo.png"));
        lblCompany.setText(logged.getCompany().getName());
        jtProjects.addMouseListener(ml);
        jtTasks.addMouseListener(mlt);
        printTasksTable();
        reloadData();
    }

    MouseListener ml = new MouseListener() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                int row = jtProjects.getSelectedRow();
                List<Project> projects = logged.getCompany().getProjects();
                JLabel label = (JLabel) jtProjects.getValueAt(row, 0);
                Project p = logged.getProjectFromName(label.getText());
                if (p != null) {
                    jpProjects.setVisible(false);
                    printTasksTable(p);
                    jpTasks.setVisible(true);
                }
            }
        }

        @Override
        public void mousePressed(MouseEvent e) { /**/ }

        @Override
        public void mouseReleased(MouseEvent e) { /**/ }

        @Override
        public void mouseEntered(MouseEvent e) { /**/ }

        @Override
        public void mouseExited(MouseEvent e) { /**/ }
    };
    MouseListener mlt = new MouseListener() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                int row = jtTasks.getSelectedRow();
                
                String taskName = String.valueOf(jtTasks.getValueAt(row, 0));
                String projectName = String.valueOf(jtTasks.getValueAt(row, 1));
                Task t = logged.getTaskFromName(taskName, projectName);
                
                jdTask.setTitle(t.getName());
                jdTask.setIconImage(new ImageIcon("logo.png").getImage());

                txtTaskName.setText(t.getName());
                txtTaskDesc.setText(t.getDesc());
                
                jdTask.setLocationRelativeTo(null);
                jdTask.setVisible(true);
           }
        }

        @Override
        public void mousePressed(MouseEvent e) { /**/ }

        @Override
        public void mouseReleased(MouseEvent e) { /**/ }

        @Override
        public void mouseEntered(MouseEvent e) { /**/ }

        @Override
        public void mouseExited(MouseEvent e) { /**/ }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pnlOptions = new javax.swing.JDialog();
        jdTask = new javax.swing.JDialog();
        txtTaskName = new javax.swing.JLabel();
        txtTaskDesc = new javax.swing.JLabel();
        btnCloseTask = new javax.swing.JButton();
        jpApp = new javax.swing.JPanel();
        ico = new javax.swing.JLabel();
        btnTareas = new javax.swing.JButton();
        btnProjects = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpProjects = new javax.swing.JPanel();
        jspProjects = new javax.swing.JScrollPane();
        jtProjects = new javax.swing.JTable();
        jpTasks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTasks = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        btnChat = new javax.swing.JButton();
        btnMeet = new javax.swing.JButton();
        jpRef = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRefAccept = new javax.swing.JButton();
        txtRefUser = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        pnlOptions.setMinimumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions.getContentPane());
        pnlOptions.getContentPane().setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jdTask.setMinimumSize(new java.awt.Dimension(300, 270));
        jdTask.setResizable(false);

        txtTaskName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTaskName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtTaskDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCloseTask.setText("Cerrar");
        btnCloseTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdTaskLayout = new javax.swing.GroupLayout(jdTask.getContentPane());
        jdTask.getContentPane().setLayout(jdTaskLayout);
        jdTaskLayout.setHorizontalGroup(
            jdTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdTaskLayout.createSequentialGroup()
                .addGroup(jdTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdTaskLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnCloseTask, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdTaskLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jdTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTaskDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jdTaskLayout.setVerticalGroup(
            jdTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdTaskLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTaskDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCloseTask, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jpApp.setMinimumSize(new java.awt.Dimension(800, 600));
        jpApp.setLayout(null);

        ico.setMinimumSize(new java.awt.Dimension(100, 100));
        jpApp.add(ico);
        ico.setBounds(50, 50, 100, 100);

        btnTareas.setText("Tareas");
        btnTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasActionPerformed(evt);
            }
        });
        jpApp.add(btnTareas);
        btnTareas.setBounds(40, 200, 120, 40);

        btnProjects.setText("Proyectos");
        btnProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectsActionPerformed(evt);
            }
        });
        jpApp.add(btnProjects);
        btnProjects.setBounds(40, 280, 120, 40);

        btnOptions.setText("Opciones");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });
        jpApp.add(btnOptions);
        btnOptions.setBounds(40, 360, 120, 40);

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jpApp.add(btnExit);
        btnExit.setBounds(40, 440, 120, 40);

        jpProjects.setLayout(null);

        jspProjects.setBorder(null);
        jspProjects.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspProjects.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jtProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Proyectos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspProjects.setViewportView(jtProjects);
        if (jtProjects.getColumnModel().getColumnCount() > 0) {
            jtProjects.getColumnModel().getColumn(0).setResizable(false);
        }

        jpProjects.add(jspProjects);
        jspProjects.setBounds(0, 0, 510, 450);

        jLayeredPane1.add(jpProjects);
        jpProjects.setBounds(0, 0, 506, 449);

        jpTasks.setLayout(null);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jtTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarea", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTasks);
        if (jtTasks.getColumnModel().getColumnCount() > 0) {
            jtTasks.getColumnModel().getColumn(0).setResizable(false);
            jtTasks.getColumnModel().getColumn(1).setResizable(false);
        }

        jpTasks.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 510, 450);

        jLayeredPane1.add(jpTasks);
        jpTasks.setBounds(0, 0, 510, 450);

        jpApp.add(jLayeredPane1);
        jLayeredPane1.setBounds(230, 80, 510, 450);

        jLabel2.setText("Empresa:");
        jpApp.add(jLabel2);
        jLabel2.setBounds(30, 560, 60, 20);
        jpApp.add(lblCompany);
        lblCompany.setBounds(90, 560, 130, 20);

        btnChat.setText("Abrir Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        jpApp.add(btnChat);
        btnChat.setBounds(630, 550, 110, 30);

        btnMeet.setText("Abrir Reunion");
        btnMeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeetActionPerformed(evt);
            }
        });
        jpApp.add(btnMeet);
        btnMeet.setBounds(450, 550, 140, 30);

        jpRef.setMinimumSize(new java.awt.Dimension(800, 600));
        jpRef.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa a tu empresa");
        jpRef.add(jLabel1);
        jLabel1.setBounds(285, 137, 260, 58);

        btnRefAccept.setText("Aceptar");
        btnRefAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefAcceptActionPerformed(evt);
            }
        });
        jpRef.add(btnRefAccept);
        btnRefAccept.setBounds(360, 440, 120, 40);

        txtRefUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtRefUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRefUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefUserActionPerformed(evt);
            }
        });
        jpRef.add(txtRefUser);
        txtRefUser.setBounds(290, 240, 250, 100);

        jMenu4.setText("GestY");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setMnemonic('T');
        jMenuItem1.setText("Tareas");
        jMenuItem1.setToolTipText("Ir a Tareas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setMnemonic('P');
        jMenuItem2.setText("Proyectos");
        jMenuItem2.setToolTipText("Ir a Proyectos");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Opciones");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRefUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefUserActionPerformed

    private void btnRefAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefAcceptActionPerformed
        if(gc.setUserRef(logged, txtRefUser.getText())){
            reloadApp();
            loadApp();
        }
    }//GEN-LAST:event_btnRefAcceptActionPerformed

    private void btnTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasActionPerformed
        jpProjects.setVisible(false);
        jpTasks.setVisible(true);
        
        printTasksTable();
    }//GEN-LAST:event_btnTareasActionPerformed

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
        // TODO add your handling code here:        
        pnlOptions.setVisible(true);
    }//GEN-LAST:event_btnOptionsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exitApp();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectsActionPerformed
        jpTasks.setVisible(false);
        updateProjectsTable();
        jpProjects.setVisible(true);
    }//GEN-LAST:event_btnProjectsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        exitApp();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        pnlOptions.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        String empresa = logged.getCompany().getName();
        topic = "gesty/" + empresa.toLowerCase().replace(' ', '-');
        openChat(topic);
    }//GEN-LAST:event_btnChatActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void btnMeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeetActionPerformed
        try {
            // Verificar si el Desktop es compatible con la acción de abrir el navegador
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                
                Desktop.getDesktop().browse(new URI("https://meet.jit.si/" + "gesty-" + logged.getCompany().getName().toLowerCase().replace(' ', '-')));
        } else {
            // Si no es compatible, puedes manejarlo de alguna otra manera (por ejemplo, abrir el enlace en un enlace etiquetado en tu aplicación)
            System.out.println("El navegador web no es compatible en este sistema.");
            }
        } catch (Exception e) {
            // Manejo de excepciones si ocurre algún error al abrir el navegador
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMeetActionPerformed

    private void btnCloseTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseTaskActionPerformed
        jdTask.setVisible(false);
    }//GEN-LAST:event_btnCloseTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialLiteTheme()));
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //
            }
        });
        
    }

    public void setLogged(Empleado logged){
        this.logged = logged;
    }
    public Empleado getLogged(){
        return this.logged;
    }
    public GestyConnector getConnector(){
        return this.gc;
    }
    public void setConnector(GestyConnector gc){
        this.gc = gc;
    }
    public void checkRef(){
        if(gc.hasRef(this.logged)){
            app.jpApp.setVisible(true);
            app.jpRef.setVisible(false);
        }else{
            app.jpApp.setVisible(false);
            app.jpRef.setVisible(true);
        }
    }

    public void reloadApp(){
        Thread wait = new Thread( () -> {
            try{
                Thread.sleep(1000);
            }catch(InterruptedException e){
                e.printStackTrace();
            }
        });
        wait.run();
        System.out.println("DEBUG: " + "WIP -> FUNCTION TO UPDATE APP WHEN UPDATE COMPANY_REF");
    }
    public void loadApp(){
        jpRef.setVisible(false);
        jpApp.setVisible(true);
    }
    
    public void exitApp(){
        System.exit(0);
    }
    
    public void openChat(String topic){
        Chat chat = new Chat(logged, topic);
        chat.setLocationRelativeTo(null);
        chat.setVisible(true);
    }
    
    public void printTasksTable(Project project){
        DefaultTableModel model = (DefaultTableModel) jtTasks.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        List<Task> tasks = project.getTasks();
        if(tasks != null){
            tasks.forEach(t -> {
                model.addRow(new Object[]{t.getName(), project.getName()});
            });
        }

    }
    
    public void printTasksTable(){
        List<Project> projects = logged.getProjects();
        DefaultTableModel model = (DefaultTableModel) jtTasks.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        if(projects != null){
            if(!projects.isEmpty()){
                projects.forEach(p -> {
                    System.out.println(p.getName());
                    if(!p.getTasks().isEmpty()){
                        List<Task> tasks = p.getTasks();
                        tasks.forEach(t -> {
                            model.addRow(new Object[]{t.getName(), p.getName()});
                        });
                    }
                });
            }
        }
        jpProjects.setVisible(false);
        jpTasks.setVisible(true);
    }

    public void getData(){
        boolean loading = false;
        Empleado emp = this.logged;
        if(emp.getCompany() == null){
            emp.setCompany();
        }
        if(emp.getCompany().getProjects().isEmpty() && !loading){
            loading = true;
            emp.setProjects();
            emp.getProjects().forEach(p -> {
                p.setTasks(p.getTasks(logged));
            });
            loading = false;
        }

        if(!emp.getCompany().getProjects().isEmpty() && !loading){
            if(!emp.getCompany().getProjects().isEmpty()){
                loading = true;
                emp.getCompany().getProjects().forEach(p -> p.getTasks(logged));
                loading = false;
            }
        }
    }

    public void reloadData(){
        Thread t = new Thread( () -> {
            while(true){
                getData();             
                updateTaskTable();
                updateProjectsTable();
                try{
                    Thread.sleep(5000);
                }catch(InterruptedException e){
                    e.printStackTrace();
                }
            }
        });
        t.start();
    }
    
    public void updateTaskTable(){
        List<Project> projects = logged.getProjects();
        DefaultTableModel model = (DefaultTableModel) jtTasks.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }

        if(projects != null){
            if(!projects.isEmpty()){
                projects.forEach(p -> {
                    System.out.println(p.getName());
                    if(!p.getTasks().isEmpty()){
                        List<Task> tasks = p.getTasks();
                        tasks.forEach(ta -> {
                            model.addRow(new Object[]{ta.getName(), p.getName()});
                        });
                    }
                });
            }
        }
        
        
    }
    
    public void updateProjectsTable(){
        List<Project> projects = gc.getProjects(logged);
        DefaultTableModel model = (DefaultTableModel) jtProjects.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        
        for (Project p : projects) {
            JLabel label = new JLabel(p.getName());
            TableCellRenderer renderer = new LabelTableCellRenderer();
            jtProjects.getColumnModel().getColumn(0).setCellRenderer(renderer);
            model.addRow(new JLabel[] { label });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnCloseTask;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMeet;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnProjects;
    private javax.swing.JButton btnRefAccept;
    private javax.swing.JButton btnTareas;
    private javax.swing.JLabel ico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDialog jdTask;
    private javax.swing.JPanel jpApp;
    private javax.swing.JPanel jpProjects;
    private javax.swing.JPanel jpRef;
    private javax.swing.JPanel jpTasks;
    private javax.swing.JScrollPane jspProjects;
    private javax.swing.JTable jtProjects;
    private javax.swing.JTable jtTasks;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JDialog pnlOptions;
    private javax.swing.JTextField txtRefUser;
    private javax.swing.JLabel txtTaskDesc;
    private javax.swing.JLabel txtTaskName;
    // End of variables declaration//GEN-END:variables
}
